version: "3.9"
services:
  redisui:
    image: redislabs/redisinsight
    restart: always
    labels:
      traefik.enable: 'true'
      traefik.docker.network: 'webgateway'
      traefik.http.routers.redisui.rule: "Host(`redis.${DEV_HOST_DOMAIN:-local}`)"
    networks:
      - development
      - webgateway

networks:
  webgateway:
    name: webgateway
  development:
    name: development