sudo: required

language: bash

services:
  - docker

branches:
  only:
    - master

script:
  - bash ./scripts/build.sh stack/mysql --force --build
  - bash ./scripts/build.sh stack/nginx --force --build
  - bash ./scripts/build.sh stack/php71 --force --build

after_success:
  - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  - bash ./scripts/build.sh stack/mysql --force --push
  - bash ./scripts/build.sh stack/nginx --force --push
  - bash ./scripts/build.sh stack/php71 --force --push