sudo: required

language: bash

services:
  - docker

branches:
  only:
    - master

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - bash ./scripts/build.sh stack/mysql --force --build --push
  - bash ./scripts/build.sh stack/nginx --force --build --push
  - bash ./scripts/build.sh stack/php71 --force --build --push
  - bash ./scripts/build.sh stack/php72 --force --build --push
  - bash ./scripts/build.sh stack/php73 --force --build --push
