language: ruby

services:
  - docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    ./scripts/build.sh mysql --force --push
    ./scripts/build.sh nginx --force --push
    ./scripts/build.sh php71 --force --push
    fi

script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    ./scripts/build.sh mysql --force --build
    ./scripts/build.sh nginx --force --build
    ./scripts/build.sh php71 --force --build
    fi