# Author: Bert Oost <hello@bertoost.com>
version: "3.3"
services:
  traefik:
    image: traefik:v1.7
    container_name: traefik
    restart: always
    command: "--web --docker --docker.domain=${DEV_HOST_DOMAIN} --docker.watch=true --docker.exposedbydefault=false --logLevel=DEBUG"
    ports:
      - "${TRAEFIK_PORT_HTTP:-80}:80"
      - "${TRAEFIK_PORT_HTTPS:-443}:443"
    labels:
      traefik.enable: 'true'
      traefik.port: '8080'
      traefik.frontend.rule: 'Host:traefik.${DEV_HOST_DOMAIN}'
      traefik.docker.network: 'webgateway'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    networks:
      - webgateway

  nginx:
    image: ${DOCKER_USERNAME:-bertoost}/nginx:1.17-dev
    container_name: nginx
    restart: always
    links:
      - php71:php71
      - php72:php72
      - php73:php73
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./data/nginx:/etc/nginx/conf.d/custom
      - ${PROJECTS_DIR-./projects}:/var/www/html
    labels:
      traefik.enable: 'true'
      traefik.frontend.rule: 'PathPrefix:/'
      traefik.frontend.priority: '1'
      traefik.docker.network: 'webgateway'
    environment:
      DEV_HOST_DOMAIN: ${DEV_HOST_DOMAIN}
      DEV_HOST_IP: ${DEV_HOST_IP}
    env_file:
      - .env
    networks:
      - development
      - webgateway

  php71:
    image: ${DOCKER_USERNAME:-bertoost}/php:7.1-fpm-dev
    container_name: php71
    restart: always
    volumes:
      - ./logs/php71:/var/log/php71
      - ./data/composer:/home/php/.composer
      - ${PROJECTS_DIR-./projects}:/var/www/html
    links:
      - mysql
      - ${DEV_MAIL_CONTAINERNAME-postoffice}:mail.docker.local
    environment:
      BINARY_DIRECTORY: ''
      XDEBUG_HOST: ${DEV_HOST_DOMAIN}
      BLACKFIRE_HOST: ${DEV_HOST_DOMAIN}
    env_file:
      - .env
    networks:
      - development

  php72:
    image: ${DOCKER_USERNAME:-bertoost}/php:7.2-fpm-dev
    container_name: php72
    restart: always
    volumes:
      - ./logs/php72:/var/log/php
      - ./data/composer:/home/php/.composer
      - ${PROJECTS_DIR-./projects}:/var/www/html
    links:
      - mysql
      - ${DEV_MAIL_CONTAINERNAME-postoffice}:mail.docker.local
    environment:
      BINARY_DIRECTORY: ''
      XDEBUG_HOST: ${DEV_HOST_DOMAIN}
      BLACKFIRE_HOST: ${DEV_HOST_DOMAIN}
      # PHP Environment variables
      # PHP_DATE_TIMEZONE: Europe/Paris
      # PHP_MAX_EXECUTION_TIME: 60
      # PHP_MEMORY_LIMIT: 256M
      # PHP_POST_MAX_SIZE: 128M
      # PHP_UPLOAD_MAX_FILESIZE: 128M
    env_file:
      - .env
    networks:
      - development

  php73:
    image: ${DOCKER_USERNAME:-bertoost}/php:7.3-fpm-dev
    container_name: php73
    restart: always
    volumes:
      - ./logs/php73:/var/log/php
      - ./data/composer:/home/php/.composer
      - ${PROJECTS_DIR-./projects}:/var/www/html
    links:
      - mysql
      - ${DEV_MAIL_CONTAINERNAME-postoffice}:mail.docker.local
    environment:
      BINARY_DIRECTORY: ''
      XDEBUG_HOST: ${DEV_HOST_DOMAIN}
      BLACKFIRE_HOST: ${DEV_HOST_DOMAIN}
      # PHP Environment variables
      # PHP_DATE_TIMEZONE: Europe/Paris
      # PHP_MAX_EXECUTION_TIME: 60
      # PHP_MEMORY_LIMIT: 256M
      # PHP_POST_MAX_SIZE: 128M
      # PHP_UPLOAD_MAX_FILESIZE: 128M
    env_file:
      - .env
    networks:
      - development

  mysql:
    image: ${DOCKER_USERNAME:-bertoost}/mysql:${MYSQL_VERSION:-5.7}
    container_name: mysql
    restart: always
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      TZ: ${MYSQL_TIMEZONE:-Europe/Amsterdam}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-mysql}
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
      - ./logs/mysql:/var/log/mysql
    networks:
      - development

  postoffice:
    image: mailhog/mailhog
    container_name: postoffice
    restart: always
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    volumes:
      - ./data/mail:/maildir
    ports:
      - '25:1025'
    labels:
      traefik.enable: 'true'
      traefik.port: '8025'
      traefik.frontend.rule: 'Host:postoffice.${DEV_HOST_DOMAIN}'
      traefik.docker.network: 'webgateway'
    networks:
      - development
      - webgateway

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: --no-auth
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './data/portainer:/data'
    labels:
      traefik.enable: 'true'
      traefik.port: '9000'
      traefik.frontend.rule: 'Host:portainer.${DEV_HOST_DOMAIN}'
      traefik.docker.network: 'webgateway'
    networks:
      - development
      - webgateway

networks:
  webgateway:
    external:
      name: webgateway
  development:
    external:
      name: development
