# Author: Bert Oost <hello@bertoost.com>
version: "3.9"
services:
  traefik:
    image: traefik:v2.6
    container_name: traefik
    restart: always
    command: >
      --log.level=DEBUG
      --api.insecure=true
      --providers.docker=true
      --providers.docker.watch=true
      --providers.docker.exposedbydefault=false
      --entrypoints.http.address=:${TRAEFIK_PORT_HTTP:-80}
      --entrypoints.https.address=:${TRAEFIK_PORT_HTTPS:-443}
    ports:
      - "${TRAEFIK_PORT_HTTP:-80}:80"
      - "${TRAEFIK_PORT_HTTPS:-443}:443"
    labels:
      traefik.enable: 'true'
      traefik.docker.network: 'webgateway'
      traefik.http.routers.traefik.rule: "Host(`traefik.${DEV_HOST_DOMAIN:-local}`)"
      traefik.http.services.traefik.loadbalancer.server.port: 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - webgateway

  mysql:
    image: ${DOCKER_USERNAME:-bertoost}/mysql:${MYSQL_VERSION:-8.0}
    container_name: mysql
    restart: always
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      TZ: ${MYSQL_TIMEZONE:-Europe/Amsterdam}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-mysql}
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
      - ./logs/mysql:/var/log/mysql
    networks:
      - development

networks:
  webgateway:
    external: true
    name: webgateway
  development:
    external: true
    name: development
