# Author: Bert Oost <hello@bertoost.com>
version: "3.3"
services:
  nginx:
    image: bertoost/nginx:latest
    container_name: nginx
    restart: always
    links:
      - php71
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./data/nginx:/etc/nginx/conf.d/custom
      - ${PROJECTS_DIR:-./projects}:/var/www/html
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=PathPrefix:/'
      - 'traefik.frontend.priority=1'
      - 'traefik.docker.network=webgateway'
    networks:
      - default
      - webgateway

  php71:
    image: bertoost/php71:fpm-development
    container_name: php71
    restart: always
    volumes:
      - ./logs/php71:/var/log/php71
      - ./data/composer:/home/php/.composer
      - ${PROJECTS_DIR:-./projects}:/var/www/html
    links:
      - mysql
      - postoffice
    extra_hosts:
      - XDEBUG_HOST:${HOST_IP}
    environment:
      - BINARY_DIRECTORY=
      - BLACKFIRE_HOST=${HOST_DOMAIN}
    env_file:
      - .env

  mysql:
    image: bertoost/mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
      - ./logs/mysql:/var/log/mysql
    networks:
      - default
      - development

  postoffice:
    image: mailhog/mailhog
    container_name: postoffice
    restart: always
    ports:
      - 8025:8025
      - 25:1025
    networks:
      - default
      - development

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: --no-auth
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './data/portainer:/data'
    ports:
      - "8888:9000"

networks:
  webgateway:
    external:
      name: webgateway
  development:
    external:
      name: development
