# Author: Bert Oost <hello@bertoost.com>
version: "3.9"
services:
  nginx:
    image: ${DOCKER_USERNAME:-bertoost}/nginx:1.19-dev
    restart: always
    depends_on:
      - php73
      - php74
      - php80
    links:
      - php73:php73
      - php74:php74
      - php80:php80
    environment:
      DEV_HOST_DOMAIN: ${DEV_HOST_DOMAIN:-local}
    volumes:
      - sock74:/sock74
      - sock80:/sock80
      - ../../logs/nginx:/var/log/nginx
      - ../../data/nginx:/etc/nginx/conf.d/custom
      - ${PROJECTS_DIR:-../../projects}:/var/www/html
    labels:
      traefik.enable: 'true'
      traefik.docker.network: 'webgateway'
      traefik.http.routers.devstackfallback.rule: "PathPrefix(`/`)"
      traefik.http.routers.devstackfallback.priority: 1
    env_file:
      - ../../.env
    networks:
      - development
      - webgateway

  php73:
    image: ${DOCKER_USERNAME:-bertoost}/php:7.3-fpm-dev
    restart: always
    volumes:
      - ../../logs/php73:/var/log/php
      - ../../data/composer:/home/php/.composer
      - ${PROJECTS_DIR:-../../projects}:/var/www/html
    environment:
      BINARY_DIRECTORY: ''
      XDEBUG_MODE: develop,debug
      PHP_IDE_CONFIG: "serverName=fallback-php73-project"
      BLACKFIRE_HOST: ${DEV_HOST_DOMAIN}
      # PHP Environment variables
      # PHP_DATE_TIMEZONE: Europe/Paris
      # PHP_MAX_EXECUTION_TIME: 60
      # PHP_MEMORY_LIMIT: 256M
      # PHP_POST_MAX_SIZE: 128M
      # PHP_UPLOAD_MAX_FILESIZE: 128M
    env_file:
      - ../../.env
    networks:
      - development

  php74:
    image: ${DOCKER_USERNAME:-bertoost}/php:7.4-fpm-dev
    restart: always
    volumes:
      - sock74:/sock
      - ../../logs/php74:/var/log/php
      - ../../data/composer:/home/php/.composer
      - ${PROJECTS_DIR:-../../projects}:/var/www/html
    environment:
      BINARY_DIRECTORY: ''
      XDEBUG_MODE: develop,debug
      PHP_IDE_CONFIG: "serverName=fallback-php74-project"
      BLACKFIRE_HOST: ${DEV_HOST_DOMAIN}
      # PHP Environment variables
      # PHP_DATE_TIMEZONE: Europe/Paris
      # PHP_MAX_EXECUTION_TIME: 60
      # PHP_MEMORY_LIMIT: 256M
      # PHP_POST_MAX_SIZE: 128M
      # PHP_UPLOAD_MAX_FILESIZE: 128M
    env_file:
      - ../../.env
    networks:
      - development

  php80:
    image: ${DOCKER_USERNAME:-bertoost}/php:8.0-fpm-dev
    restart: always
    volumes:
      - sock80:/sock
      - ../../logs/php80:/var/log/php
      - ../../data/composer:/home/php/.composer
      - ${PROJECTS_DIR:-../../projects}:/var/www/html
    environment:
      BINARY_DIRECTORY: ''
      XDEBUG_MODE: develop,debug
      PHP_IDE_CONFIG: "serverName=fallback-php80-project"
      BLACKFIRE_HOST: ${DEV_HOST_DOMAIN}
      # PHP Environment variables
      # PHP_DATE_TIMEZONE: Europe/Paris
      # PHP_MAX_EXECUTION_TIME: 60
      # PHP_MEMORY_LIMIT: 256M
      # PHP_POST_MAX_SIZE: 128M
      # PHP_UPLOAD_MAX_FILESIZE: 128M
    env_file:
      - ../../.env
    networks:
      - development

volumes:
#  projects:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: ${PROJECTS_DIR:-../../projects}
  sock74:
  sock80:

networks:
  webgateway:
    external: true
    name: webgateway
  development:
    external: true
    name: development