version: "3.3"
services:
  traefik:
    image: traefik:v1.4.1
    container_name: traefik
    restart: always
    networks:
      - webgateway
    command: --web --docker --docker.domain=${DEV_HOST_DOMAIN} --docker.watch=true --docker.exposedbydefault=false --logLevel=DEBUG
    ports:
      - "80:80"
      - "443:443"
      - "9090:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

networks:
  webgateway:
    external:
      name: webgateway
